version: '3.8'

services:
  db:
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testyml
    ports:
      - '5432:5432' # container:local